---
- name: "Install packages"
  ansible.builtin.dnf:
    name: redis
    state: latest
  become: true

- name: "Start and enable services"
  ansible.builtin.systemd:
    name: redis
    state: started
    enabled: yes
  become: true