---
- name: Install packages
  ansible.builtin.dnf:
    name: nginx
    state: present
  become: true

- name: Start and enable services
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
  become: true
