---
- name: Install prerequisites
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  become: true
  with_items:
    - apt-transport-https
    - software-properties-common
    - wget

- name: Add influxdb apt-key
  ansible.builtin.apt_key:
    url: 'https://repos.influxdata.com/influxdata-archive.key'
    state: present
  become: true

- name: Add influx repo
  ansible.builtin.apt_repository:
    repo: 'deb https://repos.influxdata.com/debian stable main'
    state: present
    filename: influxdb
    update_cache: true
  become: true

- name: Install influxdb
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  become: true
  with_items:
    - influxdb2

- name: start and enable service
  ansible.builtin.systemd_service:
    name: influxdb
    enabled: true
    state: started
    daemon_reload: true
  become: true
