---
- name: Add RPM fusion for ffmpeg
  ansible.builtin.dnf:
    name: "{{ item }}"
    disable_gpg_check: true
    state: present
  with_items:
    - epel-release
    - https://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm
  become: true
  notify: reboot

- name: Install ffmpeg and jellyfin
  ansible.builtin.dnf:
    name: "{{ item }}"
    disable_gpg_check: true
    state: present
    enablerepo: crb # CodeReady linux Builder repo - part of epel
  become: true
  with_items:
    - ffmpeg
    - https://repo.jellyfin.org/releases/server/centos/stable/server/jellyfin-server-10.8.9-1.el7.x86_64.rpm
    - https://repo.jellyfin.org/releases/server/centos/stable/web/jellyfin-web-10.8.9-1.el7.noarch.rpm
    - https://repo.jellyfin.org/releases/server/centos/stable/server/jellyfin-10.8.9-1.el7.x86_64.rpm

- name: Add jellyfin user to video, render groups
  ansible.builtin.user:
    user: jellyfin
    append: true
    groups:
      - video
      - render
  become: true

- name: Enable and start jellyfin
  ansible.builtin.systemd:
    name: jellyfin
    state: started  
    enabled: true
  become: true