---
- name: Install apache
  ansible.builtin.apt:
    name: apache2
    state: present
  become: true

- name: Start and enable service
  ansible.builtin.systemd_service:
    name: apache2
    state: started
    enabled: true
    daemon_reload: true
  become: true
