## Must login from console once and run the following command to allow connection as root
## echo "PermitRootLogin yes" >> /etc/ssh/sshd_config && systemctl restart sshd
---
- name: Install sudo
  ansible.builtin.apt:
    name: sudo
    update_cache: yes
    cache_valid_time: 3600
    state: latest
  remote_user: root

- name: Create ansible user
  ansible.builtin.user:
    name: "ansible"
    state: present
    shell: "/bin/bash"
  remote_user: root

- name: Upload ssh key
  ansible.posix.authorized_key:
    user: "ansible"
    state: present
    key: "{{ lookup('file', '/home/kevin/.ssh/ansible.pub') }}"
  remote_user: root

- name: Add ansible to sudoers
  ansible.builtin.copy:
    src: sudoer_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
  remote_user: root

- name: Disallow connection as root
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: "PermitRootLogin yes"
    state: absent
  remote_user: root
  notify: handler_restart_sshd