---
- name: Bootstrap container
  hosts: lldap
  remote_user: root
  roles:
    - root_ansibleuser
  tags:
    - bootstrap

- name: Set up lldap
  hosts: lldap
  tags:
    - main
  tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name: '{{ item }}'
        state: present
      become: true
      with_items:
        - nodejs
    
    - name: Download thelounge deb
      ansible.builtin.get_url:
        dest: '/tmp/thelounge.deb'
        url: 'https://github.com/thelounge/thelounge-deb/releases/download/v4.4.1/thelounge_4.4.1_all.deb'

    - name: Install thelounge deb
      ansible.builtin.apt:
        deb: '/tmp/thelounge.deb'
      become: true



https://download.opensuse.org/repositories/home:/Masgalor:/LLDAP/Debian_12/amd64/lldap_0.5.0-1+2.1_amd64.deb