---
- name: Create lxc-bind group
  ansible.builtin.group:
    name: lxc-bind
    gid: 10000
    state: present
  become: true

- name: Set up locale for utf8 - otherwise filenames with symbols aren't regognized correctly
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present
  become: true

- name: set as default locale
  ansible.builtin.command:
    cmd: localectl set-locale LANG=en_US.UTF-8
  become: true

- name: Add bindmount to ct config on pxe host
  ansible.builtin.lineinfile:
    path: '/etc/pve/lxc/{{ ct_id }}.conf'
    line: 'mp0: /mnt/nfs_media/,mp=/mnt/media'
    state: present
  become: true
  delegate_to: icebox
  notify: handler_reboot

# Execute restart handler right away
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
