---
# Root is used instead of a system user here.
# Ran into issues with yarn, dependencies, permissions, etc
- name: Install prerequisite packages
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  become: true
  with_items:
    - git
    - nodejs
    - npm

- name: Install yarn package
  ansible.builtin.npm:
    name: yarn
    state: present
    global: true
  become: true

- name: Clone actualserver git repo
  ansible.builtin.git:
    repo: 'https://github.com/actualbudget/actual-server.git'
    dest: /actual-server
    force: true
  become: true

# This is commented out for the time being and must be performed manually.
# The yarn module utilizes a flag (--non-interactive) that is deprecated and throws an error
####
- name: Use yarn to install packages required by actual
  command:
   chdir: /actual-server
   cmd: 'yarn install'
  become: true

- name: Copy actual.service systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/actual.service
    src: actual.service
    owner: root
    group: root
    mode: '755'
  become: true

- name: Enable and start actual service
  ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    state: restarted
    name: actual
  become: true
