---
- name: Create database for authelia
  ansible.builtin.include_role:
    name: postgres
  vars:
    db_name: "authelia"
    db_user: "authelia"
    db_password: "{{ authelia_db_password }}"

- name: Create user/group for authelia
  ansible.builtin.include_role:
    name: systemuser
  vars:
    systemuser_name: "authelia"

- name: Create /usr/bin/authelia
  ansible.builtin.file:
    path: /usr/bin/authelia
    state: directory
  become: true

- name: Install authelia
  ansible.builtin.unarchive:
    src: https://github.com/authelia/authelia/releases/download/v4.37.2/authelia-v4.37.2-linux-amd64.tar.gz
    dest: /usr/bin/authelia
    remote_src: true
    group: authelia
    owner: authelia
  become: true

- name: Copy systemd service
  ansible.builtin.copy:
    src: authelia.service
    dest: /etc/systemd/system/authelia.service
  become: true

- name: Create /etc/authelia
  ansible.builtin.file:
    path: /etc/authelia
    state: directory
    owner: authelia
    group: authelia
  become: true

- name: Deploy config
  ansible.builtin.template:
    src: authelia_config.yml.j2
    dest: /etc/authelia/configuration.yml
    group: authelia
    owner: authelia
    mode: 0600
  become: true
  become_user: authelia

- name: Start/enable authelia
  ansible.builtin.systemd:
    name: authelia.service
    state: started
    enabled: true
    daemon_reload: true
  become: true

- name: Deploy proxy config
  ansible.builtin.include_role:
    name: traefik
  vars:
    traefik_service: authelia
    app_port: 9091