---
- name: Create database for authelia
  ansible.builtin.include_role:
    name: postgres
  vars:
    db_name: "authelia"
    db_user: "authelia"
    db_password: "{{ authelia_db_password }}"

- name: Create user/group for authelia
  ansible.builtin.include_role:
    name: systemuser
  vars:
    systemuser_name: "authelia"

- name: Create /usr/bin/authelia
  ansible.builtin.file:
    path: /usr/bin/authelia
    state: directory

- name: Install authelia
  ansible.builtin.unarchive:
    src: https://github.com/authelia/authelia/releases/download/v4.37.5/authelia-v4.37.5-linux-amd64.tar.gz
    dest: /usr/bin/authelia
    remote_src: true
    group: authelia
    owner: authelia
    extra_opts: [authelia-linux-amd64]

- name: Copy systemd service
  ansible.builtin.copy:
    src: authelia.service
    dest: /etc/systemd/system/authelia.service

- name: Start/enable authelia
  ansible.builtin.systemd:
    name: authelia.service
    state: started
    enabled: true
    daemon_reload: true