---
- name: Install Dependencies
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  become: true
  with_items:
    - wget
    - curl
    - sqlite3

- name: Create readarr user / add to lxc-bind group
  ansible.builtin.user:
    name: readarr
    uid: 10000
    create_home: true
    append: true
    groups: readarr,lxc-bind
  become: true

- name: Create application install folder
  ansible.builtin.file:
    path: /var/lib/readarr
    owner: readarr
    group: readarr
    state: directory
  become: true

- name: Download readarr tarball
  ansible.builtin.get_url:
    dest: '/tmp/readarr.tar.gz'
    url: 'https://readarr.servarr.com/v1/update/develop/updatefile?os=linux&runtime=netcore&arch=x64'
  become: true

- name: Extract readarr tarball
  ansible.builtin.unarchive:
    src: /tmp/readarr.tar.gz
    dest: /opt/
    remote_src: yes
  become: true

- name: Set ownership of readarr folder
  ansible.builtin.file:
    path: /opt/Readarr
    owner: readarr
    group: readarr
    recurse: true
  become: true

- name: Copy systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/readarr.service
    src: readarr.service
  notify: handler_restartReadarr
  become: true

- name: Enable and start service
  ansible.builtin.systemd_service:
    name: readarr
    enabled: true
    state: started
    daemon_reload: true
  become: true
