---
- name: Install qbittorrent-nox (and git to clone vuetorrentui)
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  become: true
  with_items:
    - qbittorrent-nox
    - git

- name: Create home for qbit user / add to lxc-bind group
  ansible.builtin.user:
    name: qbit
    create_home: true
    uid: 10000
    append: true
    groups: qbit,lxc-bind
  become: true

- name: Copy systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/qbittorrent.service
    src: qbittorrent.service
  notify: handler_restartQbittorrent
  become: true

- name: Enable and start qbit service
  ansible.builtin.systemd_service:
    name: qbittorrent
    enabled: true
    state: started
    daemon_reload: true
  become: true

- name: Install vuetorrent (alternate ui) # must set this in webui as well
  ansible.builtin.git:
    repo: 'https://github.com/VueTorrent/VueTorrent.git'
    dest: /home/qbit/vuetorrent
    force: true
    version: latest-release
    single_branch: true
  become: true
  become_user: qbit
