---
http:
  routers:
    omv:
      rule: Host(`omv.sladnet.xyz`)
      service: omv
      tls:
        certResolver: letsencrypt
        domains:
          - main: "sladnet.xyz"
            sans:
              - "*.sladnet.xyz"
  services:
      omv:
        loadBalancer:
          servers:
            - url: "http://192.168.1.213"
