# This is untested. 
# I figure this will suffice for documentation until I 
# actually need to set up a proxmox host again
---
- name: Set up proxmox - requires ansible user with api key
  hosts: icebox
  remote_user: root

  tasks:
    - name: Setup pci passthrough
      ansible.builtin.include_tasks:
        file: vfio.yml

    - name: Setup pci passthrough
      ansible.builtin.include_tasks:
        file: vfio.yml

    - name: Disable subscription nag
      shell: sed -Ezi.bak "s/(Ext.Msg.show\(\{\s+title: gettext\('No valid sub)/void\(\{ \/\/\1/g" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
    # notify systemctl restart pveproxy.service