---
- name: Proxmox host - bootstrap as root
  hosts: icebox
  remote_user: root
  tags:
    - bootstrap

  tasks:
    - name: Setup repos
      ansible.builtin.include_tasks:
        file: tasks/repos.yml
    
    - name: Set up ansible user
      ansible.builtin.include_role:
        name: root_ansibleuser

    # syntax here is wrong. Not sure how to escape the shell command
    #- name: Disable subscription nag
    #  shell: sed -Ezi.bak "s/(Ext.Msg.show\(\{\s+title: gettext\('No valid sub)/void\(\{ \/\/\1/g" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js

    - name: Restart pveproxy service
      ansible.builtin.systemd_service:
        name: pveproxy
        state: restarted

- name: Proxmox host - Remainder of setup
  hosts: icebox
  tags:
    - main

  tasks:
    # I don't want to run this right now on my production 
    # system until I know it works
    #
    #- name: Setup vfio
    #  ansible.builtin.include_tasks:
    #    file: tasks/vfio.yml

    - name: Mount NFS Share
      ansible.posix.mount:
        src: "{{ hostvars['truenas'].ansible_host }}:/mnt/EZ14/media"
        path: /mnt/nfs_media
        opts: rw,sync,soft
        boot: false
        state: mounted
        fstype: nfs
      become: true