---
- name: Remove default repos
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  with_items:
    - "/etc/apt/sources.list.d/pve-enterprise.list"
    - "/etc/apt/sources.list.d/ceph.list"
  remote_user: root

# Debian nonfree are added for microcode updates
- name: Add non subscription and nonfree repos
  ansible.builtin.apt_repository:
    repo: '{{ item }}'
    state: present
  with_items:
    - "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
    - "deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription"
    - "deb http://deb.debian.org/debian bookworm non-free"
    - "deb http://deb.debian.org/debian bookworm-updates non-free"
    - "deb http://deb.debian.org/debian-security/ bookworm-security non-free"
  remote_user: root