---
- name: upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: true
  notify: reboot

- name: "Install required packages for python/pip"
  ansible.builtin.dnf:
    name: "{{item}}"
    state: latest
  become: true
  with_items: 
    - python-setuptools
    - python-pip