---
- name: System update
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true
  become: true
  notify: Reboot

- name: Install required packages for python/pip
  ansible.builtin.dnf:
    name:
      - python-setuptools
      - python-pip
    state: present
  become: true

- name: General utilities for most hosts
  ansible.builtin.dnf:
    name:
      - tar
    state: present
  become: true
  with_items:
    - tar
