---
- name: Traefik reverse proxy
  hosts: traefik

  roles:
    - common

  tasks:
    - name: Install Traefik
      ansible.builtin.unarchive:
        src: https://github.com/traefik/traefik/releases/download/v2.9.9/traefik_v2.9.9_linux_amd64.tar.gz
        dest: /usr/local/bin
        remote_src: true
      become: true
      register: restart_needed

    - name: Create user/group for traefik
      ansible.builtin.include_role:
        name: systemuser
      vars:
        systemuser_name: "traefik"

    - name: Set port binding capability on Traefik
      community.general.capabilities:
        path: /usr/local/bin/traefik
        capability: cap_net_bind_service+ep
        state: present
      become: true

    - name: Create /etc/traefik
      ansible.builtin.file:
        path: /etc/traefik
        state: directory
        group: traefik
        owner: traefik
        mode: '600'
      become: true

    - name: Touch acme.json
      ansible.builtin.file:
        path: /etc/traefik/acme.json
        group: traefik
        owner: traefik
        mode: '600'
        state: touch
      become: true
      become_user: traefik

    - name: Create /etc/traefik/config
      ansible.builtin.file:
        path: /etc/traefik/config
        state: directory
        group: traefik
        owner: traefik
        mode: '600'
      become: true

    - name: Create Traefik config file
      ansible.builtin.template:
        src: traefik.yml.j2
        dest: /etc/traefik/traefik.yml
        mode: "0644"
      become: true
      become_user: traefik
      notify: Restart traefik

    ## Eventually this should be moved to use traefik role
    - name: Copy proxy configs
      ansible.builtin.template:
        src: "{{ item }}.yml.j2"
        dest: "/etc/traefik/config/{{ item }}.yml"
        mode: "0755"
      become: true
      become_user: traefik
      with_items:
        - proxmox
        - dashboard
        - truenas
      notify: Restart traefik

    - name: Copy systemd service file to server
      ansible.builtin.template:
        src: traefik.service.j2
        dest: /etc/systemd/system/traefik.service
        mode: "0644"
      become: true
      notify: Restart traefik

  handlers:
    - name: Restart traefik
      ansible.builtin.systemd:
        name: traefik
        state: restarted
        daemon_reload: true
      become: true
