- name: start traefik
  systemd:
    name: traefik
    state: started
    enabled: true
  become: true

- name: restart traefik
  systemd:
    name: traefik
    state: restarted
    daemon_reload: true
  become: true