---
- name: Copy proxy configs
  ansible.builtin.template:
    src: "http.yml.j2"
    dest: "/etc/traefik/config/{{ traefik_service }}.yml"
    mode: "0755"
  become: true
  become_user: traefik
  notify:
    - restart traefik
  delegate_to: traefik