---
- name: Install Traefik
  ansible.builtin.unarchive:
    src: https://github.com/traefik/traefik/releases/download/v2.9.9/traefik_v2.9.9_linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: true
  notify:
    - restart traefik

- name: Create Traefik group
  ansible.builtin.group:
    name: traefik
    state: present

- name: Create Traefik user
  ansible.builtin.user:
    name: traefik
    group: traefik
    shell: /sbin/nologin
    state: present
    create_home: false

- name: Set port binding capability on Traefik
  community.general.capabilities:
    path: /usr/local/bin/traefik
    capability: cap_net_bind_service+ep
    state: present

- name: Create /etc/traefik
  file:
    path: /etc/traefik
    state: directory

- name: touch acme.json
  file:
    path: /etc/traefik/acme.json
    group: traefik
    owner: traefik
    mode: "600"
    state: touch

- name: Copy Traefik config
  ansible.builtin.copy:
    src: config
    dest: /etc/traefik/config
    mode: "0755"
  notify:
    - restart traefik

- name: Create Traefik config file
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: /etc/traefik/traefik.yml
    mode: "0644"
  notify:
    - restart traefik

- name: Copy systemd service file to server
  ansible.builtin.template:
    src: traefik.service.j2
    dest: /etc/systemd/system/traefik.service
    mode: "0644"
  notify:
    - restart traefik
