- name: Install remirepo
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
    disable_gpg_check: true
  with_items:
    - epel-next-release
    - https://rpms.remirepo.net/enterprise/remi-release-9.rpm


# this is for firefly. If another lamp stack is needed, move packages to firefly as needed
- name: Install required packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - php82-php
    - php82-php-bcmath
    - php82-php-intl
    - php82-php-curl
    - php82-php-zip
    - php82-php-sodium
    - php82-php-gd
    - php82-php-xml
    - php82-php-mbstring
    - php82-php-pgsql
    - composer
    - unzip  # needed for installing (firefly) from composer
    - git