- name: "Install postgres"
  dnf: "name={{ item }} state=present"
  with_items:
    - postgresql
    - postgresql-server

- name: "Install python package to enable ansible to operate on postgres"
  pip: "name={{ item }}  state=present"
  with_items:
    - psycopg2-binary
