---
- name: "Install postgres"
  dnf:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - postgresql
    - postgresql-server

- name: "Install postgres"
  pip:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - psycopg2-binary