- name: "Install required packages"
  import_tasks: install.yml

- name: "Initialize PostgreSQL"
  import_tasks: init.yml

- name: "Create database for required application"
  import_tasks: create_db.yml