---
- name: Install postgres
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  become: true
  with_items:
    - postgresql
    - python3-psycopg2

- name: Start and enable postgres
  ansible.builtin.systemd_service:
    name: postgresql
    state: started
    daemon_reload: true
    enabled: true
  become: true

- name: Create db user
  community.general.postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  become: true
  become_user: postgres

- name: Create app database
  community.general.postgresql_db:
    state: present
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
  become: true
  become_user: postgres

- name: Allow md5 connection for the db user
  community.general.postgresql_pg_hba:
    dest: "/etc/postgresql/15/main/pg_hba.conf"
    contype: host
    databases: all
    method: md5
    users: "{{ db_user }}"
    create: true
  become: true
  become_user: postgres
  notify: Restart postgres

# Execute restart handler right away
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
