---
- name: Create app database
  community.general.postgresql_db:
    state: present
    name: "{{ db_name }}"
  become: true
  become_user: postgres
  delegate_to: postgres

- name: Create db user
  community.general.postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  become: true
  become_user: postgres
  delegate_to: postgres

- name: Grant db user access to app db
  community.general.postgresql_privs:
    type: database
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    grant_option: false
    privs: all
  become: true
  become_user: postgres
  delegate_to: postgres

- name: Allow md5 connection for the db user
  community.general.postgresql_pg_hba:
    dest: "~/data/pg_hba.conf"
    contype: host
    databases: "{{ db_name }}"
    address: "{{ ansible_host }}"
    method: md5
    users: "{{ db_user }}"
    create: true
  become: true
  become_user: postgres
  notify: Restart postgres
  delegate_to: postgres

# Execute restart handler right away
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
