---
- name: Main postgres database
  hosts: postgres

  roles:
    - common

  tasks:
    - name: Install postgres
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - postgresql
        - postgresql-server

    - name: Install pip packages to talk to postgres
      ansible.builtin.pip:
        name: psycopg2-binary
        state: present
      become: true

    - name: Find out if postgresql is initialized
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      become: true
      register: postgres_data

    - name: Initialize postgresql
      ansible.builtin.command: "postgresql-setup initdb"
      become: true
      when: not postgres_data.stat.exists
      changed_when: false

    - name: Allow connections on all interfaces
      community.postgresql.postgresql_set:
        name: listen_addresses
        value: '*'
      become: true
      become_user: postgres
      notify: Restart postgres

    - name: Start and enable services
      ansible.builtin.systemd:
        name: postgresql
        state: started
        enabled: true
      become: true

  handlers:
    - name: Restart postgres
      ansible.builtin.systemd:
        name: postgresql
        state: restarted
      become: true
