---
- name: Pihole
  hosts: pihole

  roles:
    - common

  tasks:
    - name: Check for pihole binary
      ansible.builtin.stat:
        path: /usr/local/bin/pihole
      register: pihole_binary

    - name: Set fact if installed
      ansible.builtin.set_fact:
        pihole_installed: "{{ pihole_binary.stat.exists | default(false) }}"

    - name: Create /etc/pihole
      ansible.builtin.file:
        path: /etc/pihole
        state: directory
        mode: '700'
      become: true

    - name: Deploy configVars
      ansible.builtin.template:
        src: setupVars.conf.j2
        dest: /etc/pihole/setupVars.conf
        mode: '700'
      become: true
      when: not pihole_installed
      notify: reboot  # this may or may not be necessary

    - name: Download install script
      ansible.builtin.get_url:
        url: https://install.pi-hole.net
        dest: /etc/pihole/pihole-install.sh
        mode: u+rwx
      become: true
      when: not pihole_installed

    - name: Run install script
      ansible.builtin.command: /etc/pihole/pihole-install.sh --unattended
      when: not pihole_installed
      become: true
      environment:
        PIHOLE_SKIP_OS_CHECK: "true"  # support centos but not rocky huh?
      changed_when: true

    - name: Copy wildcard dns record
      ansible.builtin.template:
        src: wildcard.j2
        dest: /etc/dnsmasq.d/03-custom-dns.conf
        mode: '600'
      become: true
      notify: reboot
