- name: Firefly
  hosts: firefly

  roles:
    - common
    - postgres
    - apache
    - php
    - redis
    - traefik

  tasks:
    - name: Create working directory
      ansible.builtin.file:
        path: /var/www/html/firefly-iii
        state: directory
        owner: apache
        group: apache
        mode: '775'
      become: true
      become_user: apache

    - name: "Find out if firefly is installed with compose"
      ansible.builtin.stat:
        path: "/var/www/html/firefly-iii/storage"
      register: ffcomposed
      become: true

    - name: Install firefly with php compose
      community.general.composer:
        command: create-project
        arguments: grumpydictator/firefly-iii /var/www/html/firefly-iii 6.0.6
        working_dir: /var/www/html/firefly-iii
        no_dev: true
        prefer_dist: true
        executable: /usr/bin/php82  # this is how remirepo installs it
      become: true
      become_user: apache
      when: not ffcomposed.stat.exists

    - name: Deploy firefly config
      ansible.builtin.template:
        src: .env.j2
        dest: /var/www/html/firefly-iii/.env
        owner: apache
        group: apache
        mode: '600'
      notify: Restart apache
      become: true
      become_user: apache

    # What's changed from default? Document root and allow access to files in /var/www/html
    - name: Deploy apache config
      ansible.builtin.copy:
        src: httpd.conf
        dest: /etc/httpd/conf/httpd.conf
        owner: apache
        group: apache
        mode: '600'
      notify: Restart apache
      become: true
      become_user: apache

    - name: Init database (1/3)
      ansible.builtin.command:
        chdir: /var/www/html/firefly-iii
        cmd: "php82 artisan migrate:refresh --seed"
      become: true
      become_user: apache
      changed_when: false
      notify: Restart apache

    - name: Init database (2/3)
      ansible.builtin.command:
        chdir: /var/www/html/firefly-iii
        cmd: "php82 artisan firefly-iii:upgrade-database"
      become: true
      become_user: apache
      changed_when: false
      notify: restart apache

    - name: Init database (3/3)
      ansible.builtin.command:
        chdir: /var/www/html/firefly-iii
        cmd: "php82 artisan passport:install"
      become: true
      become_user: apache
      changed_when: false
      notify: restart apache
